<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-03T16:56:09 IST" name="Default suite" finished-at="2025-03-03T16:56:11 IST" duration-ms="1897">
    <groups>
    </groups>
    <test started-at="2025-03-03T16:56:09 IST" name="Default test" finished-at="2025-03-03T16:56:11 IST" duration-ms="1897">
      <class name="testcases_general.TC_Sample">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:04 IST" name="beforeSuite" finished-at="2025-03-03T16:56:09 IST" duration-ms="4728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:09 IST" name="beforeTest" finished-at="2025-03-03T16:56:09 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:09 IST" name="startTestCase" finished-at="2025-03-03T16:56:09 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:09 IST" name="beforeMethod" finished-at="2025-03-03T16:56:09 IST" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signIntoAccont()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:09 IST" name="signIntoAccont" finished-at="2025-03-03T16:56:10 IST" duration-ms="1414" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:48)
at wrappers.GenericWrappers.launchApplication(GenericWrappers.java:97)
at testcases_general.TC_Sample.signIntoAccont(TC_Sample.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIntoAccont -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:10 IST" name="afterMethod" finished-at="2025-03-03T16:56:11 IST" duration-ms="342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:11 IST" name="afterTest" finished-at="2025-03-03T16:56:11 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testcases_general.TC_Sample@765d7657]" started-at="2025-03-03T16:56:11 IST" name="afterSuite" finished-at="2025-03-03T16:56:11 IST" duration-ms="614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases_general.TC_Sample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
